language: node_js
sudo: false
dist: bionic
node_js:
- '12'
- '14'
- '16'
install:
- npm install
- pip install --user awscli
script:
- npm run build
after_success:
- echo "$TRAVIS_NODE_VERSION";
notifications:
  email:
    on_success: never
    on_failure: always
